config/routes.rb
Rails.application.routes.draw do
  devise_for :users, module: "users"
  get '/login', to: 'sessions#new'
  get 'reservations', to: 'reservations#index'
  post 'reservations', to: 'reservations#create'
  resources :users
  resources :rooms do
    member do
      get 'indexRegistrationList'
    end
    resources :reservations do
      collection do
        post :confirm
      end
    end
  end
  root to: 'users#index'
  get 'area', to: 'rooms#area'
  get 'search', to: 'rooms#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  mount_uploader :image, ImageUploader
  has_many :rooms
  has_many :reservations
  validates :self_introduction, length: { maximum: 100 }
  validates :name, presence: true
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_update_path_for(resource)
    user_path(id: current_user.id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @rooms = Room.all
  end

  def show
    @users = User.find(params[:id])
  end

  def new
  end

  def edit
    @users = User.find(params[:id])
  end

  def update
    @users = User.find(params[:id])
    if @users.update(user_params)
      redirect_to edit_user_path, notice: "プロフィールを更新しました。"
    else
      render "edit", status: :unprocessable_entity
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :self_introduction, :image, :encrypted_password)
  end  


  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class= "container-field user">
    <%= render "users/shared/error_messages", resource: @users %>
    <div class= "row">
        <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
            <ul>
                <li class=""><%= link_to "アカウント", "/users/#{current_user.id}", class: "link nonactive"%></li>
                <li class="active"><%= link_to "プロフィール", edit_user_path, class: "link"%></li>
            </ul>
        </div>
        <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
            <ul>
                <li class=""><%= link_to "アカウント", "/users/#{current_user.id}", class: "link nonactive"%></li>
                <li class="active"><%= link_to "プロフィール", edit_user_path, class: "link"%></li>
            </ul>
        </div>
        <div class="col-lg-10 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <h5>プロフィール</h5>
                    </div>
                </div>
                
                <%=form_with model: @users, local: true do |f| %>
                    <div class="update-content">
                        <div class="row">
                            <div class="col-md-6 offset-md-3">
                                <div class="icon-box">
                                    <% if @users.image.present? %>
                                        <%= image_tag @users.image.thumb.url, class:"icon" %>
                                    <% else %>
                                        <%= image_tag "noimage.png", class:"icon" %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.label :image, class:"col-md-3 required-a" %>
                            <%= f.file_field :image, class:"mb-4 col-md-9", placeholder:"アイコン画像をアップロード" %>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.label :name, class:"col-md-3 required-a" %>
                            <%= f.text_field :name, class:"form-control mb-4 col-md-9", placeholder:"名前を入力" %>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.label :self_introduction, class:"col-md-3 required-a" %>
                            <%= f.text_area :self_introduction, class:"form-control mb-4 col-md-9", placeholder:"自己紹介を入力" %>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.submit nil, class:"col-md-2 btn btn-primary mx-3", value:"更新" %>
                        </div>
                    </div>
                <% end %>      
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class= "top">
  <div class= "top-main">
    <div class= "container">
      <div class="col-lg-5">
        <div class= "form-frame">
          <div class= "form-area">
            <p class= "form-area-title mb-4">Rai Shareでまだ体験したことのない旅をしよう</p>
            <div class="area_search">
                <%= form_with url: area_path, method: :get, local: true do |f| %>
                  <%= f.label :room_address, "エリア" %>
                  <%= f.text_field :room_address,placeholder: "東京" %>
                  <%= f.submit "探す", class: "btn btn-primary form-control my-3" %>
              　<% end %>
                <%= link_to "一覧", rooms_path, class: "btn btn-outline-info form-control my-3"%>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class= "container">
    <div class="panel-area m-5">
      <h1 class="section-title">おすすめのエリア</h1>
      <div class= "row">
        <div class= "panel-item col-lg-3 col-6">
          <div class= "panel-item1">
            <%= form_with url: area_path, method: :get, class:"form-panel", local: true do |f| %>
              <%= f.hidden_field :room_address, value: "東京" %>
              <%= f.submit "東京", class: "panel-btn" %>
          　<% end %>
          </div>
        </div>
        <div class= "panel-item col-lg-3 col-6">
          <div class= "panel-item2">
            <%= form_with url: area_path, method: :get, class:"form-panel", local: true do |f| %>
              <%= f.hidden_field :room_address, value: "大阪" %>
              <%= f.submit "大阪", class: "panel-btn" %>
          　<% end %>
          </div>
        </div>
        <div class= "panel-item col-lg-3 col-6">
          <div class= "panel-item3">
            <%= form_with url: area_path, method: :get, class:"form-panel", local: true do |f| %>
              <%= f.hidden_field :room_address, value: "京都" %>
              <%= f.submit "京都", class: "panel-btn" %>
          　<% end %>
          </div>
        </div>
        <div class= "panel-item col-lg-3 col-6">
          <div class= "panel-item4">
            <%= form_with url: area_path, method: :get, class:"form-panel", local: true do |f| %>
              <%= f.hidden_field :room_address, value: "札幌" %>
              <%= f.submit "札幌", class: "panel-btn" %>
          　<% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<div class= "container-field user">
    <div class= "row">
        <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
            <ul>
                <li class="active"><%= link_to "アカウント", "/users/#{current_user.id}", class: "link"%></li>
                <li class=""><%= link_to "プロフィール", edit_user_path, class: "link nonactive"%></li>
            </ul>
        </div>
        <div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
            <ul>
                <li class="active"><%= link_to "アカウント", "/users/#{current_user.id}", class: "link"%></li>
                <li class=""><%= link_to "プロフィール", edit_user_path, class: "link nonactive"%></li>
            </ul>
        </div>
        <div class= "col-md-10 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <h5>アカウント</h5>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="email">メールアドレス</label>
                        <div class="col-md-9"><%= current_user.email %></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="password">パスワード</label>
                        <div class="col-md-9">*********</div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <a class="col-md-2 btn btn-primary mx-3" href="/users/edit">編集</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>