config/routes.rb
Rails.application.routes.draw do
  devise_for :users, module: "users"
  get '/login', to: 'sessions#new'
  get 'reservations', to: 'reservations#index'
  post 'reservations', to: 'reservations#create'
  resources :users
  resources :rooms do
    member do
      get 'indexRegistrationList'
    end
    resources :reservations do
      collection do
        post :confirm
      end
    end
  end
  root to: 'users#index'
  get 'area', to: 'rooms#area'
  get 'search', to: 'rooms#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    belongs_to :user
    has_many :reservations, dependent: :destroy
    mount_uploader :room_image, ImageUploader
    validates :room_name, presence: true
    validates :room_introduction, presence: true
    validates :room_address, presence: true
    validates :room_price, presence: true, numericality: true
    validates :room_image, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @users = User.all
    @rooms = Room.all
  end

  def indexRegistrationList
    @rooms = current_user.rooms
  end

  def show
    @rooms = current_user.rooms.find(params[:id])
    @reservations = Reservation.new
  end

  def new
    @rooms = Room.new
  end

  def create
    @rooms = current_user.rooms.new(room_params)
    if @rooms.save
      redirect_to room_path(@rooms), notice: "部屋を登録しました"
    else
      render "new"
    end
  end

  def edit
    @users = User.find(params[:id])
  end

  def area
    @rooms = Room.where('room_address LIKE ?', "%#{params[:room_address]}%")
  end

  def search
    @rooms = Room.where('room_address LIKE ? OR room_name like ? OR room_introduction like ?', "%#{params[:keyword]}%", "%#{params[:keyword]}%", "%#{params[:keyword]}%")
  end

  def room_params
    params.require(:room).permit(:room_name, :room_introduction, :room_price, :room_image, :room_address, :user_id)
  end  
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/area.html.erb
<div class= "container_field room">
    <h4 class="pb-4"><%= "検索結果：#{@rooms.all.count}件" %></h4>
    <div class= "row">
        <% @rooms.each do |room| %>    
            <div class="col-sm-6 col-lg-4 col-xl-3 room-frame-inner">
                <%= link_to room, class:"link link-border" do %>
                    <div class="room-image-out">
                        <%= image_tag room.room_image.url, class:"room-show-image" %>
                    </div>
                    <div class="room-profile">
                        <p class="room-profile-name"><%= room.room_name %></p>
                        <p class="room-profile-city"><%= room.room_address %></p>
                        <p class="room-profile-price price-icon">1泊/<%= room.room_price %>円</p>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/edit.html.erb
<h1>Rooms#edit</h1>
<p>Find me in app/views/rooms/edit.html.erb</p>

app/views/rooms/index.html.erb
<div class= "container_field room">
    <h4 class="pb-4">お部屋一覧</h4>
    <div class= "row">
        <% @rooms.each do |room| %>    
            <div class="col-sm-6 col-lg-4 col-xl-3 room-frame-inner mb-5">
                <%= link_to room, class:"link link-border" do %>
                    <div class="room-image-out">
                        <%= image_tag room.room_image.url, class:"room-show-image" %>
                    </div>
                    <div class="room-profile">
                        <p class="room-profile-name"><%= room.room_name %></p>
                        <p class="room-profile-city"><%= room.room_address %></p>
                        <p class="room-profile-price price-icon">1泊/<%= room.room_price %>円</p>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/indexRegistrationList.html.erb
<div class="container-fiuld room-posts">
  <h4 class="pb-4">登録済みルーム一覧</h4>
  <table>
    <thead>
      <tr align="center">
        <th>部屋画像</th>
        <th>部屋名</th>
        <th>部屋の詳細</th>
        <th>料金</th>
        <th class= "reservation-date">作成日</th>
      </tr>
    </thead>
    <tbody>
        <% @rooms.each do |room| %>
            <tr>
                <td><%= image_tag room.room_image.url, class:"reservations-image" %></td>
                <td class="posts-name"><%= link_to room.room_name,  room, class: "link" %></td>
                <td class="posts-content"><%= room.room_introduction %></td>
                <td class="price-icon"><%= room.room_price %></td>
                <td class= "reservation-date"><%= room.created_at %></td>
            </tr>
        <% end %>
    </tbody>
  </table>
</div>

app/views/rooms/new.html.erb
<div class= "container-field user">
    <div class= "row">
        <div class=" user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <h5>ルーム情報登録</h5>
                    </div>
                </div>
                <%= render "shared/error", obj: @rooms %>
                <%=form_with model: @rooms, local: true do |f| %>
                    <div class="update-content">
                        <div class="row">
                            <%= f.label :必須, {class: "badge bg-danger me-3 my-2 w-4"} %>
                            <%= f.label :room_name, class:"col-md-3 required-a my-2" %>
                            <%= f.text_field :room_name, class:"mb-4 col-md-9", placeholder:"部屋名を入力" %>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.label :必須, {class: "badge bg-danger me-3 my-2 w-4"} %>
                            <%= f.label :room_introduction, class:"col-md-3 required-a my-2" %>
                            <%= f.text_area :room_introduction, class:"form-control mb-4 col-md-9", placeholder:"部屋の詳細を入力" %>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.label :必須, {class: "badge bg-danger me-3 my-2 w-4"} %>
                            <%= f.label :room_price, class:"col-md-3 required-a my-2" %>
                            <%= f.number_field :room_price, class:"form-control mb-4 col-md-9", placeholder:"1日あたりの料金の入力" %>
                        </div>
                    </div>
                     <div class="update-content">
                        <div class="row">
                            <%= f.label :必須, {class: "badge bg-danger me-3 my-2 w-4"} %>
                            <%= f.label :room_address, class:"col-md-3 required-a my-2" %>
                            <%= f.text_field :room_address, class:"form-control mb-4 col-md-9", placeholder:"住所を入力" %>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.label :必須, {class: "badge bg-danger me-3 my-2 w-4"} %>
                            <%= f.label :room_image, class:"col-md-3 required-a my-2" %>
                            <%= f.file_field :room_image, class:"form-control mb-4 col-md-9", placeholder:"アイコン画像をアップロード" %>
                        </div>
                    </div>
                    <div class="update-content">
                        <div class="row">
                            <%= f.submit nil, class:"col-md-2 btn btn-primary mx-3", value:"登録" %>
                        </div>
                    </div>
                <% end %>      
            </div>
        </div>
    </div>
</div>
        

app/views/rooms/seach.html.erb
<div class= "container_field room">
    <h4 class="pb-4"><%= "検索結果：#{@rooms.all.count}件" %></h4>
    <div class= "row">
        <% @rooms.each do |room| %>    
            <div class="col-sm-6 col-lg-4 col-xl-3 room-frame-inner">
                <%= link_to room, class:"link link-border" do %>
                    <div class="room-image-out">
                        <%= image_tag room.room_image.url, class:"room-show-image" %>
                    </div>
                    <div class="room-profile">
                        <p class="room-profile-name"><%= room.room_name %></p>
                        <p class="room-profile-city"><%= room.room_address %></p>
                        <p class="room-profile-price price-icon">1泊/<%= room.room_price %>円</p>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/search.html.erb
<div class= "container_field room">
    <h4 class="pb-4"><%= "検索結果：#{@rooms.all.count}件" %></h4>
    <div class= "row">
        <% @rooms.each do |room| %>    
            <div class="col-sm-6 col-lg-4 col-xl-3 room-frame-inner">
                <%= link_to room, class:"link link-border" do %>
                    <div class="room-image-out">
                        <%= image_tag room.room_image.url, class:"room-show-image" %>
                    </div>
                    <div class="room-profile">
                        <p class="room-profile-name"><%= room.room_name %></p>
                        <p class="room-profile-city"><%= room.room_address %></p>
                        <p class="room-profile-price price-icon">1泊/<%= room.room_price %>円</p>
                    </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="container room-show">
    <%= render "shared/error", obj: @reservations %>
    <div class="row">
        <div class="col-md-8">
        <%= image_tag @rooms.room_image.url, class:"room-show-image" %>
        <div class="room-show-detile">
            <div class="room-show-detile-content">
            <h3>部屋名</h3>
            <p class="room-show-profile-name"><%= @rooms.room_name %></p>
            </div>
            <div class="room-show-detile-content">
            <h3>住所</h3>
            <p class="room-show-profile-address"><%= @rooms.room_address %></p>
            </div>
        </div>
        <div class="room-show-detile-content">
        <h3>部屋の詳細</h3>
        <p><%= @rooms.room_introduction %></p>
        </div>
        </div>
        <div class="col-md-4">
            <div class="room-show-nav">
                <h5 class="price-icon"><%= "#{@rooms.room_price} / 日" %></h5>
                <div class="room-show-date-select">
                    <%= form_with url: confirm_room_reservations_path(@rooms), lokal: true do |f| %>
                        <%= f.hidden_field :room_id, value: @rooms.id %>
                        <%= f.hidden_field :user_id, value: @rooms.user_id %>
                        <%= f.label :room_start_date, "開始日" %>
                        <%= f.date_field :room_start_date, class:"form-control mb-4" %>
                        <%= f.label :room_end_date, "終了日" %>
                        <%= f.date_field :room_end_date, class:"form-control mb-4" %>
                        <%= f.label :room_number, "人数" %>
                        <%= f.number_field :room_number, class:"form-control mb-4" %>
                        <%= f.submit"予約する", class:"btn btn-primary form-control" %> 
                    <% end %>
                </div>
            </div>
        </div>
  </div>
</div>