config/routes.rb
Rails.application.routes.draw do
  devise_for :users, module: "users"
  get '/login', to: 'sessions#new'
  get 'reservations', to: 'reservations#index'
  post 'reservations', to: 'reservations#create'
  resources :users
  resources :rooms do
    member do
      get 'indexRegistrationList'
    end
    resources :reservations do
      collection do
        post :confirm
      end
    end
  end
  root to: 'users#index'
  get 'area', to: 'rooms#area'
  get 'search', to: 'rooms#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RaiShare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class= "header">
      <div class= "header-inner">
        <div class= "header-left-nav">
          <%= link_to "RaiShare", root_path, class: "mx-3 link title" %>
          <div class="area_search1">
            <%= form_with url: area_path, method: :get, local: true do |f| %>
              <%= f.text_field :room_address,placeholder: "エリア" %>
              <%= f.submit :area, class: "area_btn" %>
          　<% end %>
          </div>
          <div class="keyword">
            <%= form_with url: search_path, method: :get, local: true do |f| %>
              <%= f.text_field :keyword,placeholder: "キーワード" %>
              <%= f.submit :search, class: "area_btn" %>
            <% end %>
          </div>
        </div>
        <div class= "header-right-nav">
          <% if user_signed_in? %>
            <div class= "dropdown"> 
              <div class="header_name_icon">
                <button class="dropdown__btn" id="dropdown__btn"><%= current_user.name %></button>
                <div class="header-icon-box">
                    <% if current_user.image.present? %>
                        <%= image_tag current_user.image.thumb.url, class:"icon" %>
                    <% else %>
                        <%= image_tag "noimage.png", class:"icon" %>
                    <% end %>
                </div>
              </div>
              <div class="dropdown__body" id="dropdown__body">
                <ul class="dropdown__list">
                  <li class="dropdown__item"><%= link_to "ルーム登録", new_room_path, class: "dropdown__item-link"%></li>
                  <li class="dropdown__item"><%= link_to "予約済みルーム一覧", reservations_path, class: "dropdown__item-link"%></li>
                  <li class="dropdown__item"><%= link_to "登録済みルーム一覧", "/rooms/#{current_user.id}/indexRegistrationList", class: "dropdown__item-link"%></li>
                  <li class="dropdown__item"><%= link_to "設定", "/users/#{current_user.id}", class: "dropdown__item-link"%></li>
                  <li class="dropdown__item"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "dropdown__item-link"%></li>
                </ul>
              </div>
            </div>
            
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: "btn btn-primary mx-3 my-2" %>
            <%= link_to "登録する", new_user_registration_path, class: "btn btn-secondary" %>
          <% end %>
        </div>
      </div>
    </header>
    <div class="notice">
        <% if flash[:notice] %>
          <div class="notice1"><%= flash[:notice] %></div>
        <% end %>
    </div>
    <%= yield %>
    <footer class="footer">
    <p>© 2022 RASISHARE.INC.</p>
    </footer>
  </body>
  
</html>